<?php
/**	op-module-tutorial:/content/app/index.phtml
 *
 * @created    2025-07-31
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section data-translation="true">
	<?php OP::Html(file_get_contents('overview.md'),'div.markdown') ?>
</section>

<section data-translation="true">
	<?php OP::Html(file_get_contents('tutorial.md'),'div.markdown') ?>
</section>

<section data-translation="true">
	<?php OP::Html(file_get_contents('next.md'),'div.markdown') ?>
</section>
