<?php
/**	op-module-tutorial:/content/feedback.phtml
 *
 * @created    2025-08-11
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>

You’ve completed this chapter!<br/>
Was it easy? Was it difficult? Or was it hard to understand?<br/>
We’d love to hear your thoughts—feel free to share your feedback!<br/>

<form id="feedback">
	<textarea style="width: 40em; height: 10em"></textarea><br/>
	<button> Sent </button>
</form>

<?php
//	Complete flag
if( $dir = OP()->Unit()->Router()->Args()[0] ?? null ){
	OP()->Cookie()->Set("op-tutorial-{$dir}", true);
}
