<?php
/**	op-module-tutorial:/content/feedback.phtml
 *
 * @created    2025-08-11
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>

<div style="margin-left: 0em">

You’ve completed this chapter!<br/>
Was it easy? Was it difficult? Or was it hard to understand?<br/>
We’d love to hear your thoughts—feel free to share your feedback!<br/>

<form id="feedback">
	<textarea style="width: 40em; height: 10em"></textarea><br/>
	<button data-translation="true"> Sent </button>
</form>

</div>

<?php
//	Complete flag
if( $args = OP()->Unit()->Router()->Args() ?? [] ){
	$key  = 'op-tutorial-' . join('-', $args);
	OP()->Cookie()->Set($key, true);
}
