<?php
/**	op-module-tutorial:/content/feedback.phtml
 *
 * @created    2025-08-11
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
if( $feedback = OP()->Request('feedback') ){
	$uri      = join('/', OP()->Unit()->Router()->Args());
	$to       = 'info@onepiece-framework.com';
	$subject  = "Feedback: {$uri}";
	$message  = $feedback;
	if( $sendmail = OP()->Mail($to, $subject, $message) ){
		$feedback = '';
	}
	D($feedback, $uri, $to, $subject, $message);
}

?>

<div style="margin-left: 0em">

<section class="markdown" data-translation="true">
<h1>Feedback</h1>

You’ve completed this chapter!<br/>
Was it easy? Was it difficult? Or was it hard to understand?<br/>
We’d love to hear your thoughts—feel free to share your feedback!<br/>
</section>

<?php if( $sendmail ): ?>
	<P data-translation="true">Thank you for your feedback, we will take it into consideration.</P>
<?php else: ?>
<form id="feedback" method="post">
	<textarea style="width: 40em; height: 10em" name="feedback"><?= $feedback ?></textarea><br/>
	<button data-translation="true"> Sent </button>
</form>
<?php endif; ?>


</div>

<?php
//	Complete flag
if( $args = OP()->Unit()->Router()->Args() ?? [] ){
	$key  = 'op-tutorial-' . join('-', $args);
	OP()->Cookie()->Set($key, true);
}
