<?php
/**	op-module-tutorial:/content/index.phtml
 *
 * @created    2025-07-21
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section data-translate="true">
	<h1>Tutorial of ONEPIECE Framework</h1>
	<p>
		In the tutorial, we provide information step by step.<br/>
		If you need explanations for each class or method in the code, please refer to the <code>document</code>.
	</p>
	<p>
		To begin the tutorial, please click the link below.
	</p>
	<p>
		<a href="<?= OP()->URL('tutorial:/app/'); ?>">The First Tutorial: "App"</a>
	</p>
</section>
