<?php
/**	op-module-tutorial:/content/left2.php
 *
 * Once you complete the mandatory tutorials, optional tutorials will be unlocked.
 *
 * @created    2025-09-15
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
$categories = [
	'Required',
	'Core',
	'Unit',
	'Module',
	'Layout',
];

//	...
$lock   = '🔒️';
$done   = '✅️';
$undone = '📖';
$unlock = OP()->Cookie()->Get('op-tutorial-Required-CICD');

//	...
$_required = [
	'App'     => 'App',
	'HTML'    => 'HTML',
	'Request' => 'Request',
	'Router'  => 'Router',
	'CICD'    => 'CI/CD',
	'CLI'     => 'CLI',
];

?>
<?php foreach($categories as $category): ?>
	<p><?= $category ?></p>
	<ul class="menu left">
	<?php
	$icon = $lock;
	if( $category === 'Required' ){
		foreach( $_required as $file => $label ){
			$icon = OP()->Cookie()->Get("op-tutorial-{$category}-{$file}") ? $done : ($icon == $done ? $undone : $lock);
			$href = $icon != $lock ? OP()->URL("tutorial:/{$category}/{$file}"): null;
			$atag = $href ? "<a href='{$href}'>{$label}</a>" : $label;
			echo "<li><span class='icon'>{$icon}</span>{$atag}</li>";
		}
	}else if( $category === 'Core' ){
		foreach( glob( OP()->Path("asset:/core/tutorial/*.phtml") ) as $path ){
			$file = basename($path, '.phtml');
			if( $unlock ){
				$icon = OP()->Cookie()->Get("op-tutorial-{$category}-{$file}") ? $done: $undone;
			}else{
				$icon = $lock;
			}
			$href = $icon != $lock ? OP()->URL("tutorial:/{$category}/{$file}"): null;
			$atag = $href ? "<a href='{$href}'>{$file}</a>" : $file;
			echo "<li><span class='icon'>{$icon}</span>{$atag}</li>";
		}
	}else{
		//	...
		$list = [];
		$cate = strtolower($category);

		//	...
		foreach( glob( OP()->Path("asset:/{$cate}/*/tutorial/") ) as $path ){
			$path = substr($path, 0, -10);
			$path = basename($path);
			$list[] = $path;
		}

		//	...
		foreach( $list as $name ){
			if( $name === 'develop' ){
				continue;
			}
			echo "<li>{$name}";
			echo "<ul>";
			foreach( glob( OP()->Path("asset:/{$cate}/{$name}/tutorial/*.phtml") ) as $path ){
				$file = basename($path, '.phtml');
				if( $unlock ){
					$icon = OP()->Cookie()->Get("op-tutorial-{$category}-{$name}-{$file}") ? $done: $undone;
				}else{
					$icon = $lock;
				}
				$href = $icon != $lock ? OP()->URL("tutorial:/{$category}/{$name}/{$file}") : null;
				$atag = $href ? "<a href='{$href}'>{$file}</a>" : $file;
				echo "<li><span class='icon'>{$icon}</span>{$atag}</li>";
			}
			echo "</ul>";
			echo "</li>";
		}
	}
	?>
	</ul>
<?php endforeach; ?>
