<?php
/**	op-module-tutorial:/content/left.php
 *
 * Once you complete the mandatory tutorials, optional tutorials will be unlocked.
 *
 * @created    2025-07-27
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
$args = OP()->Unit()->Router()->Args();
$arg0 = $args[0] ?? null;

//	...
if( $arg0 ){
	OP()->Session()->Set(md5($arg0), true);
}

//	...
$unlock = OP()->Cookie()->Get('op-tutorial-complete');

//	Core Tutorials
$list[0] = [
	'app'      => 'App',
	'request'  => 'Request',
	'router'   => 'Router',
	'cicd'     => 'CI/CD',
	'D'        => 'D()',
//	'OP'       => 'OP()',
];

//	Bonus Tutorials
$list[1] = [
	'newworld' => 'NEW WORLD',
	'config'   => 'Config',
	'layout'   => 'Layout',
	'error'    => 'Error',
	'notice'   => 'Notice',
	'html_pass-through' => 'HTML Pass-through',
	'api'      => 'API',
	'ci'       => 'CI',
	'cd'       => 'CD',
	'form'     => 'Form',
	'database' => 'Database',
	'template' => 'Template',
	'unit'     => 'Unit',
	'module'   => 'Module',
	'webpack'  => 'WebPack',
];

?>
<ul class="menu left">
<?php foreach([0,1] as $i): ?>
	<?php foreach( $list[$i] as $dir => $label ): ?>
		<li>
			<?php
			//	...
			$href = null;
			$hash = md5($dir);

			//	...
			if( OP()->Session()->Get($hash) ){
				$href = OP()->URL("tutorial:/{$dir}/");
			}
			?>

			<?php if( $href or $unlock ): ?>
				<a href="<?= $href ?>"><?= $label ?></a>
			<?php else: ?>
				<span><?= $label ?></span>
			<?php endif; ?>
		</li>
	<?php endforeach; ?>
<?php endforeach; ?>
</ul>
