<?php
/**	op-module-tutorial:/content/yesno.phtml
 *
 * @created    2025-08-08
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

/* @var $message string */
/* @var $yes     string */

$file = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 4)[3]['file'];
$line = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 4)[3]['line'];
$hash = md5($file.' #'.$line);
$hash = substr($hash, 0, 8);

//	...
if( OP()->Session()->Get($hash) ){
	echo '<div class="yes">';
	echo "👍";
	if( $yes ?? null ){ echo " <span id='{$hash}' data-translation='true'>{$yes}</span>"; }
	echo '<br/>';
	echo '</div>';
	return true;
}

?>
<section class="yesno">
	<p data-translation="true"><?= $message ?></p>
	<span class="button"><a href="?hash=<?= $hash ?>#<?= $hash ?>"><span data-translation="true">Yes</span></a></span>
	<span class="button"><a href="javascript:void(0)" class="no"><span data-translation="true">No</span></a></span>

	<form id="feedback" style="display:none; margin-top: 1.5em;">
		<p data-translation="true">Please sent your feedback.</p>
		<textarea style="width: 40em; height: 10em"></textarea><br/>
		<button data-translation="true"> Sent </button>
	</form>
</section>
