<?php
/**	op-module-tutorial:/content/api/index.phtml
 *
 * @created    2025-08-04
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
# Sending and receiving APIs is easy

## Installing the API Unit

```sh
php app.php _develop/git/unit/add name=api url=https://github.com/onepiece-framework/op-unit-api.git
```

## Get the request

GET, POST, and JSON can all be retrieved using `OP()->Request()`.
XML is not supported.

```php
D( OP()->Request() );
```

## Send

Send always sends JSON:

```php
OP()->Unit()->API()->Out();
```

Add a value to JSON:

```php
OP()->Unit()->API()->Result('key', $value);
```

Add an error to JSON:

```php
OP()->Unit()->API()->Error('key', $value);
```

To add a Admin value:

```php
OP()->Unit()->API()->Admin('key', $value);
```
</section>

<section class="markdown" data-translation="true">
<?php OP()->Template('tutorial:/feedback.phtml') ?>
</section>