<?php
/**	op-module-tutorial:/content/Required/App.phtml
 *
 * @created    2025-09-18
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
$origin = OP()->Unit()->App()->Origin();

?>
<section class="markdown" data-translation="true">
# Welcome to the First Tutorial

In this tutorial, you will learn how the ONEPIECE Framework works step by step!
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Please click "Yes"!',
	'yes'=>"That's right!",
])){
	return;
}
?>

<section class="markdown" data-translation="true">
## "APP" Root

First, let me explain the "APP" Root.<br/>
The "APP" Root refers to the directory where the ONEPIECE application is executed.<br/>
In the case of this application, the following directory is the "APP" Root.<br/>

<pre><code>
<?= OP()->Path('app:/') ?>
</code></pre>

Please open the directory above. You should see the ONEPIECE Framework installed there.<br/>
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Were you able to open the "APP" root?',
	'yes'=>'So Good!'
])){
	return;
}
?>

<section class="markdown" data-translation="true">
Now, please check the "APP" Root.
Let me explain the following important files.

1. `LICENSE`: This is the license for the ONEPIECE Framework.
1. `README.md`: It contains instructions on how to install and start the ONEPIECE Framework.
1. `cicd`: This is the command to run CI/CD. This will be explained in detail in the CI/CD chapter.

The important files covered in this chapter are listed below.

1. `asset` directory:
    This directory contains many files required for the ONEPIECE Framework to function properly.
1. `app.php`:
    This file is the first one executed by the ONEPIECE Framework.
    Activate the ONEPIECE mechanism, and then hands over control to `index.php`.
    This is generally referred to as an "entry point".
1. `index.php`:
    This file is controls access to that directory.
    You can place an `index.php` file in each directory as needed.
    In a typical MVC architecture, this file is called the "controller".
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Did you find the files listed above?',
	'yes'=>'So very good!',
])){
	return;
}
?>

<section class="markdown" data-translation="true">
Please note that from now on, the "APP" root will be expressed as `app:/`, so please make sure to remember this!<br/>
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Did you understand app:/?',
	'yes'=>'Excellent!',
])){
	return;
}
?>

<section class="markdown" data-translation="true">
## Let's get started with development!

Please create a `test` directory in the `app:/`. The full path is as follows:

<pre><code>
<?= OP()->Path('app:/test/') ?>
</code></pre>

Inside the newly created `test` directory, create a file named `index.php`. The full path is as follows:

<pre><code>
<?= OP()->Path('app:/test/index.php') ?>
</code></pre>

Now, let’s add the code below to index.php!

```php
&lt;?php
echo "Hello, new world";
```

After saving the program, access the following URL.
The program you saved should be executed!

<pre><code>
<?php
echo $origin.OP()->URL('app:/').'test/' ;
?>
</code></pre>

</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Are <code>Hello, new world</code> is displayed?',
	'yes'=>'Congratulation!! You are now a ONEPIECE Framework developers!!!',
])){
	return;
}
?>

<section class="markdown" data-translation="true">
## Separate the "controller" and the "view"

So we're at it, let's make one more change.<br/>
In a typical MVC architecture, it's common to separate "controllers" and "views".<br/>
In the ONEPIECE Framework, the file extension for "views" must be `phtml`.<br/>
So, let's separate them into `index.php` and `view.phtml`!<br/>

Modify `index.php` as shown below. The full path to the file is as follows: `<?= OP()->Path('app:/test/index.php') ?>`

```php
&lt;?php
// echo "Hello, new world";
OP()->Template('view.phtml');
```

`OP()->Template()` is loads a file and outputs it.
In the above code, it loads `view.phtml` and outputs it.

Now, create a `view.phtml` file and add the following code.<br/>
The full path of the file to be created is as follows: `<?= OP()->Path('app:/test/view.phtml') ?>`

```html
<h1>Hello, new world!</h1>
```

Try reloading the following URL. Are the changes reflected?

```
<?php
echo $origin.OP()->URL('app:/').'test/' ;
?>

```
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Are the changes reflected?',
	'yes'=>'Perfect!',
])){
	return;
}
?>

<section class="markdown" data-translation="true">
# Key points of this chapter

In this chapter, we learned the order in which the ONEPIECE framework is executed.

We learned that `app.php` is executed first, and then `index.php`, located at the URL location, is executed.<br/>
There was no need to edit `app.php`.

All you created and edited was a `test` directory, `index.php` and `view.phtml`.<br/>

In the ONEPIECE Framework, the `index.php` file at a URL’s "End-Point" serves as the controller for that directory.

And you used `OP()->Template()`, an important feature of the ONEPIECE framework.
This will be explained in more detail in a dedicated chapter.
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',[
	'message'=>'Do you understand the role of about index.php?',
	'yes'=>'Super Great!!',
])){
	return;
}
?>

<section class="markdown" data-translation="true">
You have now mastered the basics of the ONEPIECE Framework!
With this, you should now have a solid understanding of the role of `index.php` in the ONEPIECE Framework.
There’s nothing more to learn in this chapter — you’ve mastered it perfectly!
Now, let’s move on to the next chapter!
</section>

<section class="markdown" data-translation="true">
# The first tutorial is over

<?php OP()->Template('tutorial:/feedback.phtml') ?>

In the next chapter, we will learn how to make some modifications to the controller we created in this chapter and perform more advanced control.

[➡️ Let's move on to the next chapter!](<?php echo OP()->URL('tutorial:/Required/Request') ?>)
</section>
