
# What is a module?

A module provides replaceable content.
It can be easily carried over to other websites.

# Install

```sh
php app.php _develop/git command=submodule/add type=module name=tutorial
```

You can also install it directly using Git commands without using the framework feature.

```sh
git submodule add https://github.com/TomoakiNagahara/op-module-tutorial.git asset/module/tutorial
```
