<?php
/**	op-module-tutorial:/content/database/index.phtml
 *
 * @created    2025-08-24
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
The ONEPIECE Framework provides several units for database access:

 * `op-unit-database`: Abstracts database access. Requires `op-unit-sql` to generate SQL statements.
 * `op-unit-sql`: Generates SQL statements from arrays. Database access itself is handled by `op-unit-database`.
 * `op-unit-orm`: Provides ORM functionality.
 * `op-unit-qql`: Uses the ONEPIECE Framework’s original QQL syntax.
</section>
