<?php
/**	op-module-tutorial:/content/cicd/index.phtml
 *
 * @created    2025-07-21
 * @version    1.0
 * @package    op-module-tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
# The ONEPIECE Framework includes "CI/CD"

The ONEPIECE Framework's "CI/CD" is insanely great, with all classes organically connected to "CI".<br/>
In this chapter, you will learn about the excellent "CI/CD" of the ONEPIECE Framework step by step!
</section>

<section class="markdown" data-translation="true">
## What is CI/CD

CI/CD consists of two components: CI and CD.<br/>

 * `CI`: CI is stands for Code Inspection. If the code does not pass inspection, it cannot be pushed to the repository.<br/>
 * `CD`: CD is stands for Code Delivery. Only code that passes CI will be push to the repository.<br/>
</section>

<section class="markdown" data-translation="true">
## How do you run CI/CD?

Just run the cicd command.<br/>
Enter the following command, which will run the checks automatically and only push to the repository if all checks pass:
<pre><code>./cicd</code></pre>
</section>

<section class="markdown" data-translation="true">
# Let’s try it out

 1. Open the terminal app: The `cicd` command is executed by the CLI.
 1. Change directory to the "App" root: The `cicd` command exists in the "App" root.
 1. Execute the command: Run `./cicd`.
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',['message'=>'Did the "CI/CD" run?','yes'=>'Awesome!']) ){
	return;
}
?>

<section class="markdown" data-translation="true">
## Let’s commit the changes and run "CI/CD"
Let’s commit the `test` created in the previous chapter and push it to Git!

 1. Open the terminal and navigate to the "APP" Root.
 1. Use the Git command to add the `test` directory: `git add test`
 1. Use the Git command to commit the changes: `git commit`
 1. Use the `cicd` command to push them: `./cicd`
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',['message'=>'Did the "git push" succeed?','yes'=>'Great! You are now fully master CI/CD!']) ){
	return;
}
?>

<section class="markdown" data-translation="true">
# Technical Information

## What option arguments are available for <code>cicd</code>?

The following option arguments are available for <code>cicd</code>:

<ul>
	<li><code>test=1</code>: Runs in test mode. CI will automatically <code>git stash</code> any uncommitted changes. This option allows you to test your changes before committing them.</li>
	<li><code>ci=0</code>: Skips the CI process. Use this when you only want to run CD. However, commits that have not passed code inspection will not be pushed.</li>
	<li><code>cd=0</code>: Skips the CD process. Use this when you only want to run CI.</li>
	<li><code>display=1</code>: Enables detailed output messages.</li>
	<li><code>debug=1</code>: Displays debug information.</li>
	<li><code>unit=app</code>: Runs CI only for the specified unit.</li>
	<li><code>class=App</code>: Runs CI only for the specified class.</li>
	<li><code>method=Auto</code>: Runs CI only for the specified method.</li>
</ul>
</section>

<section class="markdown" data-translation="true">
# Key Takeaway - Last Piece of Advice
In the ONEPIECE Framework, by simply running `cicd`, code inspection and pushing to the Git repository are completed automatically.
</section>

<?php
if(!OP()->Template('tutorial:/yesno.phtml',['message'=>'Did you understand the last piece of advice?','yes'=>'Super Great!!']) ){
	return;
}
?>

<section class="markdown" data-translation="true">
# The next chapter is `D()` function.

In the next chapter, you’ll get to experience one of the most amazing features of the ONEPIECE Framework!<br/>
Using `D()` will super charge your development productivity.<br/>

You’ve completed the second tutorial!
Was it difficult? Or was it easier than you expected?
We’d love to hear your thoughts-feel free to share your feedback!

<form>
<textarea></textarea>
<button> Sent </button>
</form>

In the next chapter, we’ll dive into **D()**.

[➡️ Let's move on to the next chapter: "D()"](<?php echo OP()->URL('tutorial:/D/') ?>)
</section>
